[IMP] l10n_ar_sale: arreglar presupuesto con iva incluido
ingadhoc/argentina-sale pull request #121
Opened 2023-02-07 20:47 UTC by pablohmontenegro

Task: 28700

2023-02-07 20:47 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/121).

2023-05-03 14:06 UTC, pablohmontenegro commented on l10n_ar_sale/views/sale_report_templates.xml
> +    <template id="document_tax_totals" inherit_id="account.document_tax_totals" primary="True">
no sería necesario en principio

2023-05-03 14:11 UTC, pablohmontenegro commented on l10n_ar_sale/__manifest__.py
> +        'account',
ver si corresponde remover

2023-05-03 14:11 UTC, pablohmontenegro commented on l10n_ar_sale/models/sale_order.py
> +        ver módulo l10n_ar_account_withholding. Además acá reemplazamos el método _compute_tax_totals del módulo sale original de odoo"""
llamar a super

2023-05-03 14:15 UTC, zaoral requested changes

2023-05-03 14:15 UTC, zaoral commented on l10n_ar_sale/views/sale_report_templates.xml
> +        </t>
remove this inherit

2023-05-03 14:15 UTC, zaoral commented on l10n_ar_sale/views/sale_report_templates.xml
> +
remove the new template

2023-05-03 14:15 UTC, zaoral commented on l10n_ar_sale/__manifest__.py
> +        'account',
remove dependencia

2023-05-03 14:15 UTC, zaoral commented on l10n_ar_sale/models/sale_order.py
> +        ver módulo l10n_ar_account_withholding. Además acá reemplazamos el método _compute_tax_totals del módulo sale original de odoo"""
call super()

2023-05-03 14:15 UTC, zaoral commented on l10n_ar_sale/models/sale_order.py
> +
please review if you can make it simplier

2023-08-16 20:22 UTC, zaoral approved these changes

2023-08-16 20:22 UTC, zaoral commented
@roboadhoc r+

2023-08-16 20:29 UTC, closed without merging