[MIG] l10n_ar_sale: Migration to 17.0
ingadhoc/argentina-sale pull request #142
Opened 2024-01-02 21:17 UTC by matiasperalta1

2024-01-02 21:18 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/142).

2024-02-05 18:04 UTC, pablohmontenegro requested changes

2024-02-05 18:04 UTC, pablohmontenegro commented on l10n_ar_sale/models/sale_order.py
> +        # states={'draft': [('readonly', False)], 'sent': [('readonly', False)]},
@mem-adhoc hola Maxi, cómo estás? habría que asegurarse que esto funcione bien. O sea, que en la vista sea readonly True cuando la orden de venta no se encuentre ni en 'draft' ni en 'sent'

2024-02-05 18:04 UTC, pablohmontenegro commented on l10n_ar_sale/views/l10n_ar_sale_templates.xml
> +        <!-- <span groups="account.group_show_line_subtotals_tax_included" position="replace">
@mem-adhoc esto se puede borrar?

2024-02-05 18:04 UTC, pablohmontenegro commented on l10n_ar_sale/views/l10n_ar_sale_templates.xml
> +        </t> -->
@mem-adhoc esto se puede borrar?

2024-02-05 18:04 UTC, pablohmontenegro commented on l10n_ar_sale/views/l10n_ar_sale_templates.xml
> +        <!-- <xpath expr="//span[@t-field='line.price_total']" position="attributes">
esto se puede borrar? @mem-adhoc

2024-02-05 18:04 UTC, pablohmontenegro commented on l10n_ar_sale/views/sale_report_templates.xml
> +        <!-- <t t-set="current_subtotal" t-value="current_subtotal + line.price_total" position="attributes">
@mem-adhoc esto se puede borrar?

2024-02-05 18:04 UTC, pablohmontenegro commented on l10n_ar_sale/wizards/res_config_settings_view.xml
> +        <field name="inherit_id" ref="sale.res_config_settings_view_form"/>
@mem-adhoc dejar donde estaba

2024-02-05 18:09 UTC, zaoral requested changes

2024-02-05 18:09 UTC, zaoral commented on l10n_ar_sale/models/sale_order.py
> +        # states={'draft': [('readonly', False)], 'sent': [('readonly', False)]},
ya esta en la vista. solo borrar la linea @mem-adhoc

2024-02-05 18:09 UTC, zaoral commented on l10n_ar_sale/views/sale_report_templates.xml
> +        <!-- <span groups="account.group_show_line_subtotals_tax_included" position="replace">
también los de aca para abalo, todo lo que esta en comentario

2024-02-05 18:09 UTC, zaoral commented on l10n_ar_sale/views/sale_report_templates.xml
> +        <!-- <t t-call="sale.document_tax_totals" position="attributes">
idem

2024-03-06 13:57 UTC, zaoral commented
@roboadhoc

2024-03-06 13:57 UTC, zaoral commented
@roboadhoc r+

2024-03-06 14:00 UTC, closed without merging