[FIX] l10n_ar_sale: Fix for changes in the native quotes report
ingadhoc/argentina-sale pull request #162
Opened 2024-03-26 17:38 UTC by mem-adhoc

Tarea: 34316

2024-03-26 17:39 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/162).

2024-03-27 16:57 UTC, zaoral requested changes

2024-03-27 16:57 UTC, zaoral commented on l10n_ar_sale/views/sale_report_templates.xml
> +            <td t-if="doc.vat_discriminated" name="td_taxes" t-attf-class="text-end {{ 'text-nowrap' if len(taxes) &lt; 10 else '' }}">
```suggestion
        <td name="td_taxes" position="attributes">
            <attribute name="t-if">doc.vat_discriminated</attribute>
       </td>
```

2024-03-28 16:19 UTC, zaoral commented
@roboadhoc r+

2024-03-28 16:23 UTC, closed without merging