[FIX] l10n_ar_stock: Se pisan los datos del contacto con los de la orden
ingadhoc/argentina-sale pull request #182
Opened 2024-06-05 15:51 UTC by mem-adhoc

Ticket: 74843

2024-06-05 15:52 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/182).

2024-06-10 12:53 UTC, zaoral requested changes

2024-06-10 12:53 UTC, zaoral commented on l10n_ar_stock/views/report_deliveryslip.xml
> +                <span t-out="partner" t-options='{"widget": "contact", "fields": ["address", "phone", "mobile"], "no_marker": False, "no_tag_br": False}'/>
update manifest

2024-06-10 12:54 UTC, zaoral commented on l10n_ar_stock/views/report_deliveryslip.xml
> +                <span t-out="partner" t-options='{"widget": "contact", "fields": ["address", "phone", "mobile"], "no_marker": False, "no_tag_br": False}'/>
test do not pass no_tag_br at all

2024-06-11 14:38 UTC, zaoral commented
@roboadhoc r+
@roboadhoc override=ci/runbot-oba

we need to override because external runbot error is not linking to the build

2024-06-11 14:42 UTC, closed without merging