[FIX] l10n_ar_sale: Consideramos las ventas que provienen de website
ingadhoc/argentina-sale pull request #218
Opened 2024-12-06 15:45 UTC by mem-adhoc

Ticket: 83604

2024-12-06 15:46 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/218).

2024-12-10 12:04 UTC, pablohmontenegro requested changes

2024-12-10 12:04 UTC, pablohmontenegro commented on l10n_ar_sale/models/sale_order.py
> +                if val.get('name', _('New')) == _('New') and sale_checkbook_id:
¿por que es necesario hacer 2 if? Entiendo que se podría usar un solo if como estaba antes de la modificación. además en ambos if estás consultando si existe sale_checkbook_id (entiendo que sería redundante).

2024-12-10 12:04 UTC, pablohmontenegro commented on l10n_ar_sale/models/sale_order.py
> +                # Obtenemos el talonario asociado al tipo de venta, esto lo utilizamos si la compra viene de website
Me confunde un poco el comentario, dice talonario habla de tipo de VENTA y también si la COMPRA viene del website. ¿Se trata de una compra o una venta? si es venta entonces siempre usar la palabra "venta".

2024-12-10 12:04 UTC, pablohmontenegro commented on l10n_ar_sale/models/sale_order.py
> +                if sale_checkbook_type:
```suggestion
                if sale_checkbook_type := self.env['sale.order.type'].browse(sale_order_type_id).sale_checkbook_id:
```

2024-12-10 17:43 UTC, pablohmontenegro requested changes

2024-12-10 17:43 UTC, pablohmontenegro commented on l10n_ar_sale/models/sale_order.py
> +                if val.get('name', _('New')) == _('New'):
```suggestion
            if self.env.user.has_group('l10n_ar_sale.use_sale_checkbook') and 
                  val.get('name', _('New')) == _('New') and \
                  sale_checkbook_id:
```
por que no juntar ambos if? de los contrario tenemos más cambios en el diff

2024-12-10 17:43 UTC, pablohmontenegro commented on l10n_ar_sale/models/sale_order.py
> +            elif sale_checkbook_type := self.env['sale.order.type'].browse(val.get('type_id')).sale_checkbook_id:
puede entrar en esta condición si la venta no proviene de website? tengo entendido que según el comentario de abajo solamente queremos que entre en esta condición si la venta proviene de website

2024-12-11 15:54 UTC, pablohmontenegro requested changes

2024-12-11 15:54 UTC, pablohmontenegro commented on l10n_ar_sale/models/sale_order.py
> -                    sale_checkbook.sequence_id._next() or _('New')
Hace falta cambiar esto por esto?
                val['name'] = sale_checkbook.sequence_id._next() if \
                    sale_checkbook.sequence_id else _('New')

2024-12-11 15:54 UTC, pablohmontenegro commented on l10n_ar_sale/models/sale_order.py
> +                sale_checkbook_type = self.env['sale.order.type'].browse(val.get('type_id')).sale_checkbook_id
```suggestion
            elif sale_checkbook_id := sale_checkbook_type and sale_checkbook_type.sale_checkbook_id:
```

2024-12-11 15:54 UTC, pablohmontenegro commented on l10n_ar_sale/models/sale_order.py
> +                    sale_checkbook_type.sequence_id else _('New')
```suggestion
                val['name'] = sale_checkbook_id.sequence_id._next() if \
                    sale_checkbook_id.sequence_id else _('New')
```

2024-12-11 15:54 UTC, pablohmontenegro commented on l10n_ar_sale/models/sale_order.py
> -                    sale_checkbook.sequence_id._next() or _('New')
o sea, antes usabamos or y ahora usamos if else. Lo mismo sucede abajo en el elif, aplicas la lógica de if else en lugar del or

2024-12-11 16:03 UTC, pablohmontenegro commented on l10n_ar_sale/models/sale_order.py
> +                    sale_checkbook_type.sequence_id else _('New')
tratar de usar or en lugar de if else

2024-12-11 19:11 UTC, pablohmontenegro requested changes

2024-12-11 19:11 UTC, pablohmontenegro commented on l10n_ar_sale/models/sale_order.py
> +                    sale_checkbook_type.sequence_id._next() or _('New')
```suggestion
                sale_checkbook = self.env['sale.order.type'].browse(val.get('type_id')).sale_checkbook_id
                # Obtenemos el talonario asociado al tipo de venta, esto lo utilizamos si la venta viene de website
                # O el usuario no tiene acceso a los talonarios de venta
                val['name'] = sale_checkbook and sale_checkbook.sequence_id and\
                    sale_checkbook_type.sequence_id._next() or _('New')
```
estas guardando en sale_checkbook_type el sale_checkbook_id, creo que no sería correcto nombrar a la variable como sale_checkbook_type

2024-12-11 19:20 UTC, pablohmontenegro requested changes

2024-12-11 19:20 UTC, pablohmontenegro commented on l10n_ar_sale/models/sale_order.py
> +                    sale_checkbook_type.sequence_id._next() or _('New')
```suggestion
            elif sale_checkbook_type and not sale_checkbook_id:
                sale_checkbook = self.env['sale.order.type'].browse(val.get('type_id')).sale_checkbook_id
                # Obtenemos el talonario asociado al tipo de venta, esto lo utilizamos si la venta viene de website
                # O el usuario no tiene acceso a los talonarios de venta
                val['name'] = sale_checkbook.sequence_id and\
                    sale_checkbook_type.sequence_id._next() or _('New')
```
por que no agregaríamos not self.env.user.has_group('l10n_ar_sale.use_sale_checkbook') en el elif?

2024-12-11 19:23 UTC, pablohmontenegro commented on l10n_ar_sale/models/sale_order.py
> +                    sale_checkbook_type.sequence_id._next() or _('New')
en la línea 75 existe la posibilidad de que "self.env['sale.order.type'].browse(val.get('type_id'))" de False? en ese caso si haces False.sale_checkbook_id va a arrojar piedrazo

2024-12-11 19:24 UTC, pablohmontenegro commented on l10n_ar_sale/models/sale_order.py
> +                    sale_checkbook_type.sequence_id._next() or _('New')
también sugiero como mostré en el diff sugerido cambiar el nombre de la variable sale_checkbook_type a sale_checkbook ya que estás guardando en la variable el sale_checkbook_id y no el sale_checkbook_type

2024-12-11 19:49 UTC, pablohmontenegro requested changes

2024-12-11 19:49 UTC, pablohmontenegro commented on l10n_ar_sale/models/sale_order.py
> +                sale_checkbook = self.env['sale.checkbook'].browse(sale_checkbook_id)
```suggestion
                sale_checkbook = self.env['sale.checkbook'].browse(
                    sale_checkbook_id)
```
es para que no haya cambios innecesarios en el diff

2024-12-12 11:44 UTC, pablohmontenegro requested changes
.

2024-12-12 14:07 UTC, pablohmontenegro commented
@roboadhoc r+

2024-12-12 14:10 UTC, closed without merging